---
- hosts: amazonweb
  become_user: root
  become: yes
  tasks:
    - name: 'Install Java'
      yum: name=java-1.8.0 state=latest update_cache=yes

    - name: 'Download file from S3'
      get_url: 
        url: http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.55/bin/apache-tomcat-8.5.55.tar.gz
        dest: /opt

    - name: 'Unarchive tar file'
      unarchive: 
        src: /opt/apache-tomcat-8.5.55.tar.gz
        dest: /opt
        remote_src: yes

    - name: 'start tomcat'
      command: nohup /opt/apache-tomcat-8.5.55/bin/startup.sh
